### ISSUE TITLE
提示登陆成功后弹出报错

### ISSUE THREAD

**Issue by liangjuyao** [Cp0204/ChinaTelecomMonitor#11]
Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 194, in <module>
    main()
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 127, in main
    summary = telecom.to_summary(important_data["responseData"]["data"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_class.py", line 232, in to_summary
    float(data["balanceInfo"]["indexBalanceDataInfo"]["balance"]) * 100
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by Cp0204** [comment]
邮件我你的登录账密

**Comment by Cp0204** [comment]
https://github.com/Cp0204/ChinaTelecomMonitor/issues/7
