### ISSUE TITLE
能否解决一下青龙执行下载python依赖失败的问题

### ISSUE THREAD

**Issue by xjxjin** [Cp0204/ChinaTelecomMonitor#3]
## 开始执行... 2024-06-29 00:23:46

正在尝试自动安装依赖...
Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 21, in <module>
    from telecom_class import Telecom
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_class.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 25, in <module>
    from telecom_class import Telecom
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_class.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

## 执行结束... 2024-06-29 00:25:10  耗时 84 秒

**Comment by Cp0204** [comment]
参考 https://github.com/Cp0204/quark-auto-save/issues/8#issuecomment-2075153015
