### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by SugarCarry** [Cp0204/ChinaTelecomMonitor#6]
自动登录：成功
获取主要信息：成功
Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 184, in <module>
    main()
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 121, in main
    summary = telecom.to_summary(important_data["responseData"]["data"])
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_class.py", line 209, in to_summary
    common_balance = int(data["flowInfo"]["commonFlow"]["balance"])
ValueError: invalid literal for int() with base 10: ''

## 执行结束... 2024-06-30 20:41:58  耗时 6 秒
  大佬这是什么问题？？

**Comment by Cp0204** [comment]
不清楚

**Comment by Cp0204** [comment]
提供必要信息请参考，https://github.com/Cp0204/ChinaTelecomMonitor/issues/7
