### ISSUE TITLE
提 Issue 须知

### ISSUE THREAD

**Issue by Cp0204** [Cp0204/ChinaTelecomMonitor#7]
本工具的数据是基于电信客户端接口返回的数据做适配转化，没有任何破解行为。

同时因**千人千面（不同省份的电信套餐不一样、个人的套餐有差异，返回的数据就不一样）**，而我只能根据我套餐的数据来写，没有足够的样本，就无法适配。

如果你使用中出现了报错，有两种提 Issue 方式：

1. 自行诊断问题点，针对问题点提出修改建议，甚至 PR 。
2. **清晰地提供报错 log 、出错的数据**，参考 https://github.com/Cp0204/ChinaTelecomMonitor/issues/4 
   更进一步的话可能需要邮件提供你的 token 或账号密码信息，以供我诊断。

此外，不接受其他任何形式的使用咨询，例如反例：

- https://github.com/Cp0204/ChinaTelecomMonitor/issues/1

**我乐于无偿分享，但我的时间宝贵，无法提供手把手教学或免费定制服务。**
如果你确实需要更深入的指导或个性化解决方案，我很乐意以每小时100元起的工时费用为你提供服务。

如果你有能力解决问题并PR，让大家都受益，那将十分感谢！

**Comment by fay000fay** [comment]
简化接口无法使用。

**Comment by Cp0204** [comment]
> 简化接口无法使用。

这是一个典型的反例，不提供任何问题日志和信息，只说无法使用，让你猜、算命去。很遗憾还是在提Issue须知下留言。

**Comment by sjhyxt** [comment]
多账号怎么添加？

**Comment by Cp0204** [comment]
> 多账号怎么添加？

不支持，自行修改代码

**Comment by sjhyxt** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tiger326** [comment]
我是在青龙里运行的,  运行会报错.  信息如下:
Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 214, in <module>
    main()
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 126, in main
    auto_login()
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 93, in auto_login
    if login_fail_time < 5:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'

尝试把login_fail_time 这个地方转换了一下, 目前能正常跑起来了.
第91行取值的时候, 用int函数包了一层, 看起来可以解决:

login_fail_time = int(CONFIG_DATA.get("loginFailTime", 0))
